### ISSUE TITLE
About Flops

### ISSUE THREAD

**Issue by AZZMM** [badripatro/simba#3]
Hi author, thank you for sharing your excellent work!

I have a question about the FLOPs counting.

The code writes that you count the FLOPs with the repo [mamba-minimal](https://github.com/badripatro/simba/blob/main/classification/simba.py#L56C1-L56C118) , but in mamba's [issue#110](https://github.com/state-spaces/mamba/issues/110)  the author of mamba [claimed](https://github.com/state-spaces/mamba/issues/110#issuecomment-1919470069) that the actual implementation needs much more FLOPs than simply scan in a for loop.

Can you tell me what approach you have adopted in calculating the FLOPs?
Also, what about the throughput of Simba?

Thank you.

**Comment by badripatro** [comment]
We have adopted [Mamba-minimal](https://github.com/johnma2006/mamba-minimal/blob/master/model.py ) for calculating the FLOPs.
