### ISSUE TITLE
Could you elaborate how you get the token-label-data as in the training command?

### ISSUE THREAD

**Issue by Teddy-Xiong** [badripatro/simba#5]

**Comment by liqiangniu** [comment]
Same issue. How to get token-label-data when training?

**Comment by liqiangniu** [comment]
Is this? https://github.com/zihangJiang/TokenLabeling

**Comment by badripatro** [comment]
Yes, we are using same repo for Token Labeling: https://github.com/zihangJiang/TokenLabeling
