### ISSUE TITLE
Pretrained weights in ImageNet

### ISSUE THREAD

**Issue by Ale0311** [badripatro/simba#7]
Hello, 

Congrats for your work!

Have you released the pre-trained weights on ImageNet? I plan to run som experiments for semantic segmentation and the weights for the classification task would be really helpful. 

Thanks! 

Alexandra

**Comment by badripatro** [comment]
Hi, thank you for this point. We are working on it and will get back to you asap.

**Comment by chokevin8** [comment]
Hello, are there any updates to this as when the pretrained ImageNet weights will be released? Thank you!

**Comment by EddieEduardo** [comment]
Great work !!!
Any plans to release the weights?
Thanks !!!
